title: HJin-C
description: >-
  Media Makes Space <br>
  with Hyde.
url: "https://hjin-c.github.io/"
baseurl: "/hyde"
github: HJin-C
email: hyeonjinc@gmail.com
google_analytics: "92694006"

exclude: [README.md, Gemfile, Gemfile.lock]

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
